"""Add the leads table

Lead qualification (design doc §4.9) had no storage: the platform could name
the use case and the intent but had nowhere to put a scored prospect. Each BANT
dimension keeps the caller's own words alongside the score derived from them,
so a salesperson can audit a number rather than only trust it.

Revision ID: 30bfaf8254c3
Revises: 9b3e0f1c74a2
Create Date: 2026-08-09 01:57:01.298247
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.types  # noqa: F401  (custom GUID / JSONBType columns)



revision: str = '30bfaf8254c3'
down_revision: str | None = '9b3e0f1c74a2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('business_id', app.db.types.GUID(), nullable=False),
    sa.Column('agent_id', app.db.types.GUID(), nullable=True),
    sa.Column('call_id', app.db.types.GUID(), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('interest', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('budget_score', sa.Float(), nullable=False),
    sa.Column('authority_score', sa.Float(), nullable=False),
    sa.Column('need_score', sa.Float(), nullable=False),
    sa.Column('timeline_score', sa.Float(), nullable=False),
    sa.Column('budget_answer', sa.Text(), nullable=True),
    sa.Column('authority_answer', sa.Text(), nullable=True),
    sa.Column('need_answer', sa.Text(), nullable=True),
    sa.Column('timeline_answer', sa.Text(), nullable=True),
    sa.Column('rationale', app.db.types.JSONBType(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('qualified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('crm_status', sa.String(length=20), nullable=False),
    sa.Column('crm_pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('crm_reference', sa.String(length=160), nullable=True),
    sa.Column('crm_attempts', sa.Integer(), nullable=False),
    sa.Column('crm_error', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', app.db.types.JSONBType(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['voice_agents.id'], name=op.f('fk_leads_agent_id_voice_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_leads_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['call_id'], ['call_logs.id'], name=op.f('fk_leads_call_id_call_logs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    op.create_index(op.f('ix_leads_agent_id'), 'leads', ['agent_id'], unique=False)
    op.create_index(op.f('ix_leads_business_id'), 'leads', ['business_id'], unique=False)
    op.create_index('ix_leads_business_phone', 'leads', ['business_id', 'contact_phone'], unique=False)
    op.create_index('ix_leads_business_status_score', 'leads', ['business_id', 'status', 'score', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_leads_call_id'), 'leads', ['call_id'], unique=False)
    op.create_index('ix_leads_crm_status', 'leads', ['crm_status', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_leads_deleted_at'), 'leads', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_deleted_at'), table_name='leads')
    op.drop_index('ix_leads_crm_status', table_name='leads')
    op.drop_index(op.f('ix_leads_call_id'), table_name='leads')
    op.drop_index('ix_leads_business_status_score', table_name='leads')
    op.drop_index('ix_leads_business_phone', table_name='leads')
    op.drop_index(op.f('ix_leads_business_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_agent_id'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
