"""initial schema

Revision ID: 42ad54f988ea
Revises: 
Create Date: 2026-08-08 15:23:06.057972
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.types  # noqa: F401  (custom GUID / JSONBType columns)



revision: str = '42ad54f988ea'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=80), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('plan', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings_json', app.db.types.JSONBType(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_businesses'))
    )
    op.create_index(op.f('ix_businesses_deleted_at'), 'businesses', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_businesses_slug'), 'businesses', ['slug'], unique=True)
    op.create_index('ix_businesses_status_deleted', 'businesses', ['status', 'deleted_at'], unique=False)
    op.create_table('billing_usage',
    sa.Column('business_id', app.db.types.GUID(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('plan_id', sa.String(length=30), nullable=False),
    sa.Column('minutes_used', sa.Integer(), nullable=False),
    sa.Column('included_minutes', sa.Integer(), nullable=False),
    sa.Column('overage_minutes', sa.Integer(), nullable=False),
    sa.Column('calls_count', sa.Integer(), nullable=False),
    sa.Column('base_fee_paise', sa.BigInteger(), nullable=False),
    sa.Column('overage_paise', sa.BigInteger(), nullable=False),
    sa.Column('number_rent_paise', sa.BigInteger(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('tax_paise', sa.BigInteger(), nullable=False),
    sa.Column('total_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invoice_number', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_billing_usage_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_usage')),
    sa.UniqueConstraint('business_id', 'month', name='uq_billing_usage_business_id_month')
    )
    op.create_index(op.f('ix_billing_usage_business_id'), 'billing_usage', ['business_id'], unique=False)
    op.create_index(op.f('ix_billing_usage_deleted_at'), 'billing_usage', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_billing_usage_month'), 'billing_usage', ['month'], unique=False)
    op.create_table('dnd_registry',
    sa.Column('business_id', app.db.types.GUID(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('is_dnd', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_dnd_registry_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dnd_registry')),
    sa.UniqueConstraint('business_id', 'phone_number', name='uq_dnd_business_phone')
    )
    op.create_index(op.f('ix_dnd_registry_business_id'), 'dnd_registry', ['business_id'], unique=False)
    op.create_index(op.f('ix_dnd_registry_phone_number'), 'dnd_registry', ['phone_number'], unique=False)
    op.create_table('users',
    sa.Column('business_id', app.db.types.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_users_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('business_id', 'email', name='uq_users_business_id_email')
    )
    op.create_index(op.f('ix_users_business_id'), 'users', ['business_id'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('voice_agents',
    sa.Column('business_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('use_case', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('supported_languages', app.db.types.JSONBType(), nullable=False),
    sa.Column('voice_id', sa.String(length=80), nullable=False),
    sa.Column('persona', sa.Text(), nullable=False),
    sa.Column('greeting', sa.Text(), nullable=True),
    sa.Column('fallback_message', sa.Text(), nullable=True),
    sa.Column('flow_json', app.db.types.JSONBType(), nullable=False),
    sa.Column('flow_version', sa.Integer(), nullable=False),
    sa.Column('max_call_duration_sec', sa.Integer(), nullable=False),
    sa.Column('handoff_confidence_threshold', sa.Float(), nullable=False),
    sa.Column('whatsapp_handoff_enabled', sa.Boolean(), nullable=False),
    sa.Column('recording_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_voice_agents_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voice_agents')),
    sa.UniqueConstraint('business_id', 'name', name='uq_voice_agents_business_id_name')
    )
    op.create_index(op.f('ix_voice_agents_business_id'), 'voice_agents', ['business_id'], unique=False)
    op.create_index('ix_voice_agents_business_status', 'voice_agents', ['business_id', 'status', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_voice_agents_deleted_at'), 'voice_agents', ['deleted_at'], unique=False)
    op.create_table('analytics',
    sa.Column('business_id', app.db.types.GUID(), nullable=False),
    sa.Column('agent_id', app.db.types.GUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('inbound_calls', sa.Integer(), nullable=False),
    sa.Column('outbound_calls', sa.Integer(), nullable=False),
    sa.Column('answered_calls', sa.Integer(), nullable=False),
    sa.Column('failed_calls', sa.Integer(), nullable=False),
    sa.Column('total_duration_sec', sa.BigInteger(), nullable=False),
    sa.Column('avg_duration_sec', sa.Float(), nullable=False),
    sa.Column('total_billable_minutes', sa.Integer(), nullable=False),
    sa.Column('total_cost_paise', sa.BigInteger(), nullable=False),
    sa.Column('resolved_calls', sa.Integer(), nullable=False),
    sa.Column('escalated_calls', sa.Integer(), nullable=False),
    sa.Column('handed_off_calls', sa.Integer(), nullable=False),
    sa.Column('resolution_rate', sa.Float(), nullable=False),
    sa.Column('positive_sentiment', sa.Integer(), nullable=False),
    sa.Column('neutral_sentiment', sa.Integer(), nullable=False),
    sa.Column('negative_sentiment', sa.Integer(), nullable=False),
    sa.Column('avg_confidence', sa.Float(), nullable=False),
    sa.Column('language_breakdown', app.db.types.JSONBType(), nullable=False),
    sa.Column('intent_breakdown', app.db.types.JSONBType(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['voice_agents.id'], name=op.f('fk_analytics_agent_id_voice_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_analytics_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics')),
    sa.UniqueConstraint('business_id', 'agent_id', 'date', name='uq_analytics_scope_date')
    )
    op.create_index(op.f('ix_analytics_agent_id'), 'analytics', ['agent_id'], unique=False)
    op.create_index('ix_analytics_business_date', 'analytics', ['business_id', 'date'], unique=False)
    op.create_index(op.f('ix_analytics_business_id'), 'analytics', ['business_id'], unique=False)
    op.create_index(op.f('ix_analytics_date'), 'analytics', ['date'], unique=False)
    op.create_index(op.f('ix_analytics_deleted_at'), 'analytics', ['deleted_at'], unique=False)
    op.create_table('intents',
    sa.Column('business_id', app.db.types.GUID(), nullable=False),
    sa.Column('agent_id', app.db.types.GUID(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('sample_phrases', app.db.types.JSONBType(), nullable=False),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('parameters_json', app.db.types.JSONBType(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['voice_agents.id'], name=op.f('fk_intents_agent_id_voice_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_intents_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intents')),
    sa.UniqueConstraint('business_id', 'agent_id', 'name', name='uq_intents_scope_name')
    )
    op.create_index(op.f('ix_intents_agent_id'), 'intents', ['agent_id'], unique=False)
    op.create_index(op.f('ix_intents_business_id'), 'intents', ['business_id'], unique=False)
    op.create_index(op.f('ix_intents_deleted_at'), 'intents', ['deleted_at'], unique=False)
    op.create_table('phone_numbers',
    sa.Column('business_id', app.db.types.GUID(), nullable=False),
    sa.Column('agent_id', app.db.types.GUID(), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_number_id', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('inbound_enabled', sa.Boolean(), nullable=False),
    sa.Column('outbound_enabled', sa.Boolean(), nullable=False),
    sa.Column('monthly_rent_paise', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['voice_agents.id'], name=op.f('fk_phone_numbers_agent_id_voice_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_phone_numbers_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone_numbers')),
    sa.UniqueConstraint('number', 'provider', name='uq_phone_numbers_number_provider')
    )
    op.create_index(op.f('ix_phone_numbers_agent_id'), 'phone_numbers', ['agent_id'], unique=False)
    op.create_index(op.f('ix_phone_numbers_business_id'), 'phone_numbers', ['business_id'], unique=False)
    op.create_index('ix_phone_numbers_business_status', 'phone_numbers', ['business_id', 'status', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_phone_numbers_deleted_at'), 'phone_numbers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_phone_numbers_number'), 'phone_numbers', ['number'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('business_id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_refresh_tokens_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_business_id'), 'refresh_tokens', ['business_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('call_logs',
    sa.Column('business_id', app.db.types.GUID(), nullable=False),
    sa.Column('agent_id', app.db.types.GUID(), nullable=True),
    sa.Column('phone_number_id', app.db.types.GUID(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('caller_number', sa.String(length=20), nullable=False),
    sa.Column('callee_number', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_call_id', sa.String(length=120), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('billable_minutes', sa.Integer(), nullable=False),
    sa.Column('cost_paise', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('detected_languages', app.db.types.JSONBType(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=False),
    sa.Column('primary_intent', sa.String(length=80), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('dnd_checked', sa.Boolean(), nullable=False),
    sa.Column('consent_announced', sa.Boolean(), nullable=False),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', app.db.types.JSONBType(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['voice_agents.id'], name=op.f('fk_call_logs_agent_id_voice_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_call_logs_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], name=op.f('fk_call_logs_phone_number_id_phone_numbers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_logs')),
    sa.UniqueConstraint('provider', 'provider_call_id', name='uq_call_logs_provider_provider_call_id')
    )
    op.create_index(op.f('ix_call_logs_agent_id'), 'call_logs', ['agent_id'], unique=False)
    op.create_index('ix_call_logs_business_created', 'call_logs', ['business_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_call_logs_business_id'), 'call_logs', ['business_id'], unique=False)
    op.create_index('ix_call_logs_business_status', 'call_logs', ['business_id', 'status', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_call_logs_caller_number'), 'call_logs', ['caller_number'], unique=False)
    op.create_index(op.f('ix_call_logs_deleted_at'), 'call_logs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_call_logs_provider_call_id'), 'call_logs', ['provider_call_id'], unique=False)
    op.create_table('call_recordings',
    sa.Column('business_id', app.db.types.GUID(), nullable=False),
    sa.Column('call_id', app.db.types.GUID(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('storage_bucket', sa.String(length=120), nullable=False),
    sa.Column('content_type', sa.String(length=60), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('encryption_algorithm', sa.String(length=30), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_call_recordings_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['call_id'], ['call_logs.id'], name=op.f('fk_call_recordings_call_id_call_logs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_recordings')),
    sa.UniqueConstraint('call_id', name=op.f('uq_call_recordings_call_id'))
    )
    op.create_index(op.f('ix_call_recordings_business_id'), 'call_recordings', ['business_id'], unique=False)
    op.create_index(op.f('ix_call_recordings_deleted_at'), 'call_recordings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_call_recordings_expires_at'), 'call_recordings', ['expires_at'], unique=False)
    op.create_table('conversations',
    sa.Column('business_id', app.db.types.GUID(), nullable=False),
    sa.Column('call_id', app.db.types.GUID(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('detected_intent', sa.String(length=80), nullable=True),
    sa.Column('flow_node_id', sa.String(length=80), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=120), nullable=True),
    sa.Column('metadata_json', app.db.types.JSONBType(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_conversations_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['call_id'], ['call_logs.id'], name=op.f('fk_conversations_call_id_call_logs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('call_id', 'turn_index', name='uq_conversations_call_id_turn_index')
    )
    op.create_index('ix_conversations_business_call', 'conversations', ['business_id', 'call_id'], unique=False)
    op.create_index(op.f('ix_conversations_business_id'), 'conversations', ['business_id'], unique=False)
    op.create_index(op.f('ix_conversations_call_id'), 'conversations', ['call_id'], unique=False)
    op.create_index(op.f('ix_conversations_deleted_at'), 'conversations', ['deleted_at'], unique=False)
    op.create_table('whatsapp_handoffs',
    sa.Column('business_id', app.db.types.GUID(), nullable=False),
    sa.Column('call_id', app.db.types.GUID(), nullable=False),
    sa.Column('to_number', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('context_json', app.db.types.JSONBType(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_message_id', sa.String(length=160), nullable=True),
    sa.Column('confidence_at_handoff', sa.Float(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_whatsapp_handoffs_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['call_id'], ['call_logs.id'], name=op.f('fk_whatsapp_handoffs_call_id_call_logs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_handoffs'))
    )
    op.create_index(op.f('ix_whatsapp_handoffs_business_id'), 'whatsapp_handoffs', ['business_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_handoffs_call_id'), 'whatsapp_handoffs', ['call_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_handoffs_deleted_at'), 'whatsapp_handoffs', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_handoffs_deleted_at'), table_name='whatsapp_handoffs')
    op.drop_index(op.f('ix_whatsapp_handoffs_call_id'), table_name='whatsapp_handoffs')
    op.drop_index(op.f('ix_whatsapp_handoffs_business_id'), table_name='whatsapp_handoffs')
    op.drop_table('whatsapp_handoffs')
    op.drop_index(op.f('ix_conversations_deleted_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_call_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_business_id'), table_name='conversations')
    op.drop_index('ix_conversations_business_call', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_call_recordings_expires_at'), table_name='call_recordings')
    op.drop_index(op.f('ix_call_recordings_deleted_at'), table_name='call_recordings')
    op.drop_index(op.f('ix_call_recordings_business_id'), table_name='call_recordings')
    op.drop_table('call_recordings')
    op.drop_index(op.f('ix_call_logs_provider_call_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_deleted_at'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_caller_number'), table_name='call_logs')
    op.drop_index('ix_call_logs_business_status', table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_business_id'), table_name='call_logs')
    op.drop_index('ix_call_logs_business_created', table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_agent_id'), table_name='call_logs')
    op.drop_table('call_logs')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_business_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_phone_numbers_number'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_deleted_at'), table_name='phone_numbers')
    op.drop_index('ix_phone_numbers_business_status', table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_business_id'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_agent_id'), table_name='phone_numbers')
    op.drop_table('phone_numbers')
    op.drop_index(op.f('ix_intents_deleted_at'), table_name='intents')
    op.drop_index(op.f('ix_intents_business_id'), table_name='intents')
    op.drop_index(op.f('ix_intents_agent_id'), table_name='intents')
    op.drop_table('intents')
    op.drop_index(op.f('ix_analytics_deleted_at'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_date'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_business_id'), table_name='analytics')
    op.drop_index('ix_analytics_business_date', table_name='analytics')
    op.drop_index(op.f('ix_analytics_agent_id'), table_name='analytics')
    op.drop_table('analytics')
    op.drop_index(op.f('ix_voice_agents_deleted_at'), table_name='voice_agents')
    op.drop_index('ix_voice_agents_business_status', table_name='voice_agents')
    op.drop_index(op.f('ix_voice_agents_business_id'), table_name='voice_agents')
    op.drop_table('voice_agents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_business_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dnd_registry_phone_number'), table_name='dnd_registry')
    op.drop_index(op.f('ix_dnd_registry_business_id'), table_name='dnd_registry')
    op.drop_table('dnd_registry')
    op.drop_index(op.f('ix_billing_usage_month'), table_name='billing_usage')
    op.drop_index(op.f('ix_billing_usage_deleted_at'), table_name='billing_usage')
    op.drop_index(op.f('ix_billing_usage_business_id'), table_name='billing_usage')
    op.drop_table('billing_usage')
    op.drop_index('ix_businesses_status_deleted', table_name='businesses')
    op.drop_index(op.f('ix_businesses_slug'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_deleted_at'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
