"""Add the appointments table

Appointment booking is the platform's primary use case, and it previously had
no storage: ``IntentActionType.BOOK_APPOINTMENT`` was detectable but nothing
persisted the booking. Slots are stored in UTC; the tenant's opening hours and
capacity live on ``businesses.settings_json``.

Revision ID: 5d67214240a0
Revises: 8c1f47b920de
Create Date: 2026-08-08 21:01:20.968969
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.types  # noqa: F401  (custom GUID / JSONBType columns)



revision: str = '5d67214240a0'
down_revision: str | None = '8c1f47b920de'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('business_id', app.db.types.GUID(), nullable=False),
    sa.Column('agent_id', app.db.types.GUID(), nullable=True),
    sa.Column('call_id', app.db.types.GUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('service', sa.String(length=200), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', app.db.types.JSONBType(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['voice_agents.id'], name=op.f('fk_appointments_agent_id_voice_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_appointments_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['call_id'], ['call_logs.id'], name=op.f('fk_appointments_call_id_call_logs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.create_index(op.f('ix_appointments_agent_id'), 'appointments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_appointments_business_id'), 'appointments', ['business_id'], unique=False)
    op.create_index('ix_appointments_business_phone', 'appointments', ['business_id', 'customer_phone'], unique=False)
    op.create_index('ix_appointments_business_scheduled', 'appointments', ['business_id', 'scheduled_at', 'deleted_at'], unique=False)
    op.create_index('ix_appointments_business_status', 'appointments', ['business_id', 'status', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_appointments_call_id'), 'appointments', ['call_id'], unique=False)
    op.create_index(op.f('ix_appointments_deleted_at'), 'appointments', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_deleted_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_call_id'), table_name='appointments')
    op.drop_index('ix_appointments_business_status', table_name='appointments')
    op.drop_index('ix_appointments_business_scheduled', table_name='appointments')
    op.drop_index('ix_appointments_business_phone', table_name='appointments')
    op.drop_index(op.f('ix_appointments_business_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_agent_id'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
